version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql_accounts
    restart: always
    command: 
      # - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
      - --default_time_zone=America/Sao_Paulo
    volumes:
      - ./mysql_local:/var/lib/mysql
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: accounts
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
      TZ: America/Sao_Paulo
  